# Generated by Django 5.2.6 on 2025-09-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=100)),
                ('sub_id', models.CharField(max_length=100)),
                ('prelims', models.IntegerField()),
                ('midterms', models.IntegerField()),
                ('finals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year_lvl', models.CharField(max_length=100)),
                ('adviser', models.CharField(max_length=100)),
                ('homeroom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=100)),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=100)),
                ('stu_con', models.IntegerField()),
                ('stu_pass', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100)),
                ('rooms', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=100)),
                ('prof_name', models.CharField(max_length=100)),
                ('instructor_email', models.EmailField(max_length=100)),
                ('contach', models.IntegerField()),
                ('specialized', models.CharField(max_length=100)),
            ],
        ),
    ]
