# Generated by Django 5.2.6 on 2025-09-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_id',
            name='stu_pass',
            field=models.CharField(),
        ),
    ]
