# Generated by Django 5.2.8 on 2025-11-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_student_id_user_alter_student_id_stu_pass_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
